### PR TITLE
implemented last donation date check

### LINKED ISSUE #165: [Backend] Check if last donation date is within last 3 months
## Check if last donation date is within last 3 months

**Description:**

Ideally a donor should not donate if they have already donated in last 2-3 months. So we will keep a check on our system. In this case, they must not be able to see any pending requests. Although, all other features should work.

This should be checked/updated from two ways:

1. While registering as a donor, we are taking donor's last donation date
2. After a successful donation from our platform

### PR DESCRIPTION
**Pull request by rakesh-nj**
## Description

Made changes to check if the last donation date is within 3 months

## Related Issue(s)
Fixes #165 

## Changes Made

- Implemented a last donation date check in the `ApplyAsDonorView` to enforce a 3-month restriction on blood donations.
- Integrated validation logic within the `ApplyAsDonorSerializer` to prevent donors from donating within the last 3 months.

## Screenshots (if applicable)

[Include screenshots or images that help demonstrate the changes made, especially for UI-related changes.]

## Checklist

Please review and check the following before submitting your pull request:

- [x] I have followed the [Code of Conduct](CODE_OF_CONDUCT.md).
- [x] My code follows the project's [contributing guidelines](CONTRIBUTING.md).
- [x] I have tested my changes locally and they work as expected.
- [x] I have included relevant tests for my changes.
- [x] I have updated the project documentation if necessary.
- [x] I have reviewed my code to ensure it is free of debugging or development-related code.
- [x] I have provided clear and informative commit messages.

## Contributor License Agreement

By submitting this pull request, I confirm that my contribution is made under the terms of the project's [License](LICENSE.md), and I agree to abide by the project's [Code of Conduct](CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by sayakongit** [comment]
Hi @rakesh-nj please acknowledge the comments and update the PR

**Comment by rakesh-nj** [comment]
Hi ! could you please explain me a little bit ?

**Comment by sayakongit** [comment]
@rakesh-nj sure, which part you need an explanation for?

**Comment by rakesh-nj** [comment]
Hey , what else do I need to update  ? please let me know which view has to be updated ?

**Comment by sayakongit** [comment]
I have made specific comments on code with the changes needed.

**Comment by rakesh-nj** [comment]
Sorry for my misunderstanding . I will make the changes needed.

**Comment by sayakongit** [comment]
@rakesh-nj I think you still misunderstood the comments. Please see the below comments and resolve. 

image

**Comment by rakesh-nj** [comment]
Hi @sayakongit  I have made changes . Please check

**Comment by rakesh-nj** [comment]
Hi @sayakongit Please check it out

**Comment by sayakongit** [comment]
@rakesh-nj Hi, sorry brother but I think you still haven't got the issue. I am unassigning you from this. Never mind, you can still work on other issues.

**Pull request closed without merging**
