### PR TITLE
Frontend UI Improvements

### PR DESCRIPTION
**Pull request by NeelGaji**
## Description
Fix Issue: #30
Fixed the front-end code quality. 
Improved Readability of the code along with proper naming of the components.

## Changes Made

Made different files for repeating components ensuring that code looks clean and increases readability.

## Checklist

Please review and check the following before submitting your pull request:

- [ ] I have followed the [Code of Conduct](CODE_OF_CONDUCT.md).
- [ ] My code follows the project's [contributing guidelines](CONTRIBUTING.md).
- [ ] I have tested my changes locally and they work as expected.
- [ ] I have included relevant tests for my changes.
- [ ] I have updated the project documentation if necessary.
- [ ] I have reviewed my code to ensure it is free of debugging or development-related code.
- [ ] I have provided clear and informative commit messages.

## Additional Notes (if any)

[Include any additional information, context, or notes that might be relevant to the reviewer or project maintainers.]

## Contributor License Agreement

By submitting this pull request, I confirm that my contribution is made under the terms of the project's [License](LICENSE.md), and I agree to abide by the project's [Code of Conduct](CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by sayakongit** [comment]
@NeelGaji Great work! But I think the issue is still not ready for the PR. There are scope to improve more eg. in the dashboard you can consider making the left bar as a component and use it in different pages. And please follow the [contributions guidelines](CONTRIBUTING.md) before making a commit. Looking forward to your contributions!

**Comment by NeelGaji** [comment]
> @NeelGaji Great work! But I think the issue is still not ready for the PR. There are scope to improve more eg. in the dashboard you can consider making the left bar as a component and use it in different pages. And please follow the [contributions guidelines](CONTRIBUTING.md) before making a commit. Looking forward to your contributions!


I couldn't log into the app even after running the backend. The app didn't send me an OTP to log in, so I didn't change those files as the UI was not to be changed.

**Comment by sayakongit** [comment]
> > @NeelGaji Great work! But I think the issue is still not ready for the PR. There are scope to improve more eg. in the dashboard you can consider making the left bar as a component and use it in different pages. And please follow the [contributions guidelines](CONTRIBUTING.md) before making a commit. Looking forward to your contributions!
> 
> I couldn't log into the app even after running the backend. The app didn't send me an OTP to log in, so I didn't change those files as the UI was not to be changed.

Hey @NeelGaji, you have to start the backend and setup the environment variables with your email and app password. If you are using gmail, refer this https://www.getmailbird.com/gmail-app-password/. Still if it does not run, let me know here.

**Comment by NeelGaji** [comment]
> > > @NeelGaji Great work! But I think the issue is still not ready for the PR. There are scope to improve more eg. in the dashboard you can consider making the left bar as a component and use it in different pages. And please follow the [contributions guidelines](CONTRIBUTING.md) before making a commit. Looking forward to your contributions!
> > 
> > 
> > I couldn't log into the app even after running the backend. The app didn't send me an OTP to log in, so I didn't change those files as the UI was not to be changed.
> 
> Hey @NeelGaji, you have to start the backend and setup the environment variables with your email and app password. If you are using gmail, refer this https://www.getmailbird.com/gmail-app-password/. Still if it does not run, let me know here.

Hey @sayakongit , as I carefully saw the components of the dashboards it seems that they all have different className for their styles so dividing them further into small components might not be a good option here.

**Comment by sayakongit** [comment]
@NeelGaji You are right. That was a hacky way of building the UI. This issue was to fix this problems only. You can change the `classNames` and what else you need to make smaller components until the UI/UX remains similar.

**Comment by NeelGaji** [comment]
> @NeelGaji You are right. That was a hacky way of building the UI. This issue was to fix this problems only. You can change the `classNames` and what else you need to make smaller components until the UI/UX remains similar.

That should be done really quickly. Can you help me with the OTP part as I am still not able to run the backend, just not to change the UI/UX of the app.

**Comment by SuchetanChanda** [comment]
> > @NeelGaji You are right. That was a hacky way of building the UI. This issue was to fix this problems only. You can change the `classNames` and what else you need to make smaller components until the UI/UX remains similar.
> 
> That should be done really quickly. Can you help me with the OTP part as I am still not able to run the backend, just not to change the UI/UX of the app.

Hey @NeelGaji , can you elaborate on what error you are facing while running the backend server?

**Comment by NeelGaji** [comment]
> > > @NeelGaji You are right. That was a hacky way of building the UI. This issue was to fix this problems only. You can change the `classNames` and what else you need to make smaller components until the UI/UX remains similar.
> > 
> > 
> > That should be done really quickly. Can you help me with the OTP part as I am still not able to run the backend, just not to change the UI/UX of the app.
> 
> Hey @NeelGaji , can you elaborate on what error you are facing while running the backend server?

Hey @SuchetanChanda , this is the error I am facing while starting the server.
image

**Comment by sayakongit** [comment]
Hi @NeelGaji, You aren't doing anything wrong. This is the API server so you don't need to run it in browser. Just start the server and you are good to go with the front-end. All the APIs should work now.

**Comment by SuchetanChanda** [comment]
> > > > @NeelGaji You are right. That was a hacky way of building the UI. This issue was to fix this problems only. You can change the `classNames` and what else you need to make smaller components until the UI/UX remains similar.
> > > 
> > > 
> > > That should be done really quickly. Can you help me with the OTP part as I am still not able to run the backend, just not to change the UI/UX of the app.
> > 
> > 
> > Hey @NeelGaji , can you elaborate on what error you are facing while running the backend server?
> 
> Hey @SuchetanChanda , this is the error I am facing while starting the server. image

Hey @NeelGaji , also don't forget to change the `.env.example` file for the OTP service.

**Comment by sayakongit** [comment]
@NeelGaji Any update or any blockage that you are facing? Let us solve it together if you feel so

**Comment by NeelGaji** [comment]
> @NeelGaji Any update or any blockage that you are facing? Let us solve it together if you feel so

I got a bit busy with my interviews will update you soon. :)

**Pull request closed without merging**
